SELECT a.PRODUCT_ID, b.PRODUCT_NAME, SUM(a.AMOUNT)*b.PRICE TOTAL_SALES
FROM FOOD_ORDER a INNER JOIN FOOD_PRODUCT b 
     on a.PRODUCT_ID = b.PRODUCT_ID
WHERE YEAR(a.PRODUCE_DATE) = 2022 AND MONTH(a.PRODUCE_DATE) = 5
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID