SELECT a.CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT a
WHERE CATEGORY in ('과자','국','김치','식용유')
HAVING PRICE =
(
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT b
    WHERE a.CATEGORY = b.CATEGORY
)
ORDER BY 2 DESC