SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_OUTS a INNER JOIN ANIMAL_INS b on a.ANIMAL_ID = b.ANIMAL_ID
WHERE  b.SEX_UPON_INTAKE like 'Intact%' and not a.SEX_UPON_OUTCOME like 'Intact%'
ORDER BY a.ANIMAL_ID