SELECT 
    CASE 
        WHEN DATE_FORMAT(START_DATE, '%Y-%m') = '2022-08' then 8
        WHEN DATE_FORMAT(START_DATE, '%Y-%m') = '2022-09' then 9
        WHEN DATE_FORMAT(START_DATE, '%Y-%m') = '2022-10' then 10
        END as MONTH,
    CAR_ID, COUNT(1) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  
WHERE CAR_ID in
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE DATE_FORMAT(START_DATE, '%Y-%m') between '2022-08' and '2022-10'
GROUP BY CAR_ID
HAVING COUNT(1) >= 5 
)
GROUP BY MONTH, CAR_ID
HAVING MONTH != 0
ORDER BY MONTH, CAR_ID DESC