SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW r left join MEMBER_PROFILE m on r.MEMBER_ID = m.MEMBER_ID
WHERE m.MEMBER_ID in (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING Count(1) = (
        SELECT Count(1)
        FROM REST_REVIEW r2
        GROUP BY MEMBER_ID
        ORDER BY 1 DESC
        LIMIT 1
    )
)
ORDER BY 3, 2